In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/niyarrbarman/symptom2disease/Symptom2Disease.csv

In [4]:
# ML Models on Text Dataset

import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/niyarrbarman/symptom2disease/Symptom2Disease.csv')

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (1200, 3)

   Unnamed: 0      label                                               text
0           0  Psoriasis  I have been experiencing a skin rash on my arm...
1           1  Psoriasis  My skin has been peeling, especially on my kne...
2           2  Psoriasis  I have been experiencing joint pain in my fing...
3           3  Psoriasis  There is a silver like dusting on my skin, esp...
4           4  Psoriasis  My nails have small dents or pits in them, and...

In [5]:
df.head(5)

   Unnamed: 0      label                                               text
0           0  Psoriasis  I have been experiencing a skin rash on my arm...
1           1  Psoriasis  My skin has been peeling, especially on my kne...
2           2  Psoriasis  I have been experiencing joint pain in my fing...
3           3  Psoriasis  There is a silver like dusting on my skin, esp...
4           4  Psoriasis  My nails have small dents or pits in them, and...

In [6]:
print("Columns:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nUnique Diseases:")
print(df['label'].nunique())

print("\nDisease Names:")
print(df['label'].unique())

Columns:
Index(['Unnamed: 0', 'label', 'text'], dtype='object')

Missing Values:
Unnamed: 0    0
label         0
text          0
dtype: int64

Unique Diseases:
24

Disease Names:
['Psoriasis' 'Varicose Veins' 'Typhoid' 'Chicken pox' 'Impetigo' 'Dengue'
 'Fungal infection' 'Common Cold' 'Pneumonia' 'Dimorphic Hemorrhoids'
 'Arthritis' 'Acne' 'Bronchial Asthma' 'Hypertension' 'Migraine'
 'Cervical spondylosis' 'Jaundice' 'Malaria' 'urinary tract infection'
 'allergy' 'gastroesophageal reflux disease' 'drug reaction'
 'peptic ulcer disease' 'diabetes']

In [7]:
X = df['text']
y = df['label']

print("Sample Input:\n")
print(X.iloc[0])

print("\nTarget Disease:")
print(y.iloc[0])

Sample Input:

I have been experiencing a skin rash on my arms, legs, and torso for the past few weeks. It is red, itchy, and covered in dry, scaly patches.

Target Disease:
Psoriasis

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

X_tfidf = tfidf.fit_transform(X)

print("Shape after TF-IDF:")
print(X_tfidf.shape)

Shape after TF-IDF:
(1200, 1367)

In [9]:
# Train-Test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (960, 1367)
Testing Data Shape: (240, 1367)

In [10]:
# MODEL 1: NAIVE BAYES

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb_model = MultinomialNB()

nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)

nb_accuracy = accuracy_score(y_test, y_pred_nb)

print("Naive Bayes Accuracy:", nb_accuracy)

Naive Bayes Accuracy: 0.9208333333333333

In [11]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_nb))

                                 precision    recall  f1-score   support

                           Acne       1.00      1.00      1.00        10
                      Arthritis       0.91      1.00      0.95        10
               Bronchial Asthma       0.91      1.00      0.95        10
           Cervical spondylosis       0.91      1.00      0.95        10
                    Chicken pox       0.70      0.70      0.70        10
                    Common Cold       1.00      1.00      1.00        10
                         Dengue       0.78      0.70      0.74        10
          Dimorphic Hemorrhoids       1.00      1.00      1.00        10
               Fungal infection       0.83      1.00      0.91        10
                   Hypertension       1.00      0.90      0.95        10
                       Impetigo       1.00      1.00      1.00        10
                       Jaundice       1.00      1.00      1.00        10
                        Malaria       1.00      1.00      1.00        10
                       Migraine       1.00      0.90      0.95        10
                      Pneumonia       0.71      1.00      0.83        10
                      Psoriasis       1.00      0.80      0.89        10
                        Typhoid       0.91      1.00      0.95        10
                 Varicose Veins       1.00      1.00      1.00        10
                        allergy       1.00      0.80      0.89        10
                       diabetes       1.00      0.90      0.95        10
                  drug reaction       0.86      0.60      0.71        10
gastroesophageal reflux disease       0.77      1.00      0.87        10
           peptic ulcer disease       1.00      0.80      0.89        10
        urinary tract infection       1.00      1.00      1.00        10

                       accuracy                           0.92       240
                      macro avg       0.93      0.92      0.92       240
                   weighted avg       0.93      0.92      0.92       240

In [17]:
# MODEL 2: SVM 

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", svm_accuracy)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_svm))

SVM Accuracy: 0.9583333333333334

Classification Report:

                                 precision    recall  f1-score   support

                           Acne       1.00      1.00      1.00        10
                      Arthritis       1.00      1.00      1.00        10
               Bronchial Asthma       1.00      1.00      1.00        10
           Cervical spondylosis       1.00      1.00      1.00        10
                    Chicken pox       0.82      0.90      0.86        10
                    Common Cold       1.00      1.00      1.00        10
                         Dengue       1.00      0.80      0.89        10
          Dimorphic Hemorrhoids       1.00      1.00      1.00        10
               Fungal infection       1.00      1.00      1.00        10
                   Hypertension       1.00      1.00      1.00        10
                       Impetigo       1.00      1.00      1.00        10
                       Jaundice       1.00      1.00      1.00        10
                        Malaria       1.00      1.00      1.00        10
                       Migraine       1.00      1.00      1.00        10
                      Pneumonia       0.83      1.00      0.91        10
                      Psoriasis       1.00      1.00      1.00        10
                        Typhoid       0.90      0.90      0.90        10
                 Varicose Veins       1.00      1.00      1.00        10
                        allergy       1.00      0.90      0.95        10
                       diabetes       0.82      0.90      0.86        10
                  drug reaction       0.86      0.60      0.71        10
gastroesophageal reflux disease       0.91      1.00      0.95        10
           peptic ulcer disease       0.91      1.00      0.95        10
        urinary tract infection       1.00      1.00      1.00        10

                       accuracy                           0.96       240
                      macro avg       0.96      0.96      0.96       240
                   weighted avg       0.96      0.96      0.96       240

In [28]:
# Model 3: DECISION TREE

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

dt_model = DecisionTreeClassifier(
    random_state=42,
    max_depth=20
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", round(dt_accuracy, 4))

print("\nClassification Report:\n")
print(
    classification_report(
        y_test,
        y_pred_dt,
        zero_division=0
    )
)

Decision Tree Accuracy: 0.6875

Classification Report:

                                 precision    recall  f1-score   support

                           Acne       1.00      1.00      1.00        10
                      Arthritis       1.00      1.00      1.00        10
               Bronchial Asthma       1.00      0.90      0.95        10
           Cervical spondylosis       1.00      0.90      0.95        10
                    Chicken pox       0.43      0.30      0.35        10
                    Common Cold       1.00      0.70      0.82        10
                         Dengue       0.50      0.20      0.29        10
          Dimorphic Hemorrhoids       1.00      1.00      1.00        10
               Fungal infection       0.78      0.70      0.74        10
                   Hypertension       1.00      0.40      0.57        10
                       Impetigo       1.00      0.60      0.75        10
                       Jaundice       0.89      0.80      0.84        10
                        Malaria       0.83      1.00      0.91        10
                       Migraine       0.91      1.00      0.95        10
                      Pneumonia       0.69      0.90      0.78        10
                      Psoriasis       0.71      0.50      0.59        10
                        Typhoid       0.80      0.40      0.53        10
                 Varicose Veins       1.00      1.00      1.00        10
                        allergy       1.00      0.60      0.75        10
                       diabetes       1.00      0.60      0.75        10
                  drug reaction       0.11      0.60      0.18        10
gastroesophageal reflux disease       0.73      0.80      0.76        10
           peptic ulcer disease       0.00      0.00      0.00        10
        urinary tract infection       0.75      0.60      0.67        10

                       accuracy                           0.69       240
                      macro avg       0.80      0.69      0.71       240
                   weighted avg       0.80      0.69      0.71       240

In [29]:
# ML Models on Image Dataset

import os

for dirname, dirnames, filenames in os.walk('/kaggle/input'):
    print("Folder:", dirname)

    for d in dirnames[:5]:
        print("  Subfolder:", d)

    for f in filenames[:5]:
        print("  File:", f)

    print("-"*50)

Folder: /kaggle/input
  Subfolder: datasets
  Subfolder: notebooks
--------------------------------------------------
Folder: /kaggle/input/datasets
  Subfolder: hasnainjaved
  Subfolder: niyarrbarman
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved
  Subfolder: melanoma-skin-cancer-dataset-of-10000-images
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images
  Subfolder: melanoma_cancer_dataset
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset
  Subfolder: test
  Subfolder: train
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/test
  Subfolder: benign
  Subfolder: malignant
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/test/benign
  File: melanoma_9697.jpg
  File: melanoma_10087.jpg
  File: melanoma_9618.jpg
  File: melanoma_9614.jpg
  File: melanoma_9862.jpg
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/test/malignant
  File: melanoma_10221.jpg
  File: melanoma_10267.jpg
  File: melanoma_10303.jpg
  File: melanoma_10529.jpg
  File: melanoma_10528.jpg
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/train
  Subfolder: benign
  Subfolder: malignant
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/train/benign
  File: melanoma_4922.jpg
  File: melanoma_3160.jpg
  File: melanoma_2315.jpg
  File: melanoma_1021.jpg
  File: melanoma_1352.jpg
--------------------------------------------------
Folder: /kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/train/malignant
  File: melanoma_6046.jpg
  File: melanoma_7233.jpg
  File: melanoma_8215.jpg
  File: melanoma_5115.jpg
  File: melanoma_7710.jpg
--------------------------------------------------
Folder: /kaggle/input/datasets/niyarrbarman
  Subfolder: symptom2disease
--------------------------------------------------
Folder: /kaggle/input/datasets/niyarrbarman/symptom2disease
  File: Symptom2Disease.csv
--------------------------------------------------
Folder: /kaggle/input/notebooks
  Subfolder: melihkanbay
--------------------------------------------------
Folder: /kaggle/input/notebooks/melihkanbay
--------------------------------------------------

In [31]:
# LOAD & PREPROCESS IMAGES

import os
import cv2
import numpy as np

train_path = "/kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/train"
test_path = "/kaggle/input/datasets/hasnainjaved/melanoma-skin-cancer-dataset-of-10000-images/melanoma_cancer_dataset/test"

IMG_SIZE = 64

X_train = []
y_train = []

X_test = []
y_test = []

classes = ['benign', 'malignant']

for label, category in enumerate(classes):

    folder = os.path.join(train_path, category)

    for img_name in os.listdir(folder)[:1000]:

        img_path = os.path.join(folder, img_name)

        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        X_train.append(img.flatten())

        y_train.append(label)

for label, category in enumerate(classes):

    folder = os.path.join(test_path, category)

    for img_name in os.listdir(folder)[:300]:

        img_path = os.path.join(folder, img_name)

        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        X_test.append(img.flatten())

        y_test.append(label)

X_train = np.array(X_train)
X_test = np.array(X_test)

y_train = np.array(y_train)
y_test = np.array(y_test)

print("Training Images:", X_train.shape)
print("Testing Images:", X_test.shape)

Training Images: (2000, 4096)
Testing Images: (600, 4096)

In [32]:
# MODEL 4: K-NEAREST NEIGHBOR (KNN)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# Create Model
knn_model = KNeighborsClassifier(
    n_neighbors=5
)

# Train Model
knn_model.fit(X_train, y_train)

# Predictions
y_pred_knn = knn_model.predict(X_test)

# Accuracy
knn_accuracy = accuracy_score(
    y_test,
    y_pred_knn
)

print("KNN Accuracy:", round(knn_accuracy,4))

print("\nClassification Report:\n")

print(
    classification_report(
        y_test,
        y_pred_knn,
        target_names=['benign','malignant'],
        zero_division=0
    )
)

KNN Accuracy: 0.8317

Classification Report:

              precision    recall  f1-score   support

      benign       0.79      0.91      0.84       300
   malignant       0.90      0.75      0.82       300

    accuracy                           0.83       600
   macro avg       0.84      0.83      0.83       600
weighted avg       0.84      0.83      0.83       600

In [33]:
# MODEL 5: RANDOM FOREST

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Create Model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Train Model
rf_model.fit(X_train, y_train)

# Predictions
y_pred_rf = rf_model.predict(X_test)

# Accuracy
rf_accuracy = accuracy_score(
    y_test,
    y_pred_rf
)

print("Random Forest Accuracy:", round(rf_accuracy,4))

print("\nClassification Report:\n")

print(
    classification_report(
        y_test,
        y_pred_rf,
        target_names=['benign','malignant'],
        zero_division=0
    )
)

Random Forest Accuracy: 0.8917

Classification Report:

              precision    recall  f1-score   support

      benign       0.89      0.90      0.89       300
   malignant       0.90      0.89      0.89       300

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.89      0.89      0.89       600

In [34]:
# TEXT MODELS

import pandas as pd

text_results = pd.DataFrame({
    'Model':['Naive Bayes','SVM','Decision Tree'],
    'Accuracy':[nb_accuracy, svm_accuracy, dt_accuracy]
})

text_results.sort_values(by='Accuracy', ascending=False)

           Model  Accuracy
1            SVM  0.958333
0    Naive Bayes  0.920833
2  Decision Tree  0.687500

In [35]:
# IMAGE MODELS

image_results = pd.DataFrame({
    'Model':['KNN','Random Forest'],
    'Accuracy':[knn_accuracy, rf_accuracy]
})

image_results.sort_values(by='Accuracy', ascending=False)

           Model  Accuracy
1  Random Forest  0.891667
0            KNN  0.831667